<template>
    <div class="my-nav">
        <nav-item v-for="(navInfo,index) in navList" :key="index" :nav-info="navInfo" @click.native="handleClick(navInfo.url)"/>
    </div>
</template>

<script>
    import NavItem from "./NavItem";
    export default {
        name: "MyNavigation",
        data(){
            return {
                navList:[
                    {
                        title:'Vue官方文档',
                        icon:'/docs/navIcons/vue_logo.png',
                        url:'https://cn.vuejs.org/v2/guide'
                    },
                    {
                        title:'Ant Design Vue',
                        icon:'/docs/navIcons/antd_vue.ico',
                        url:'https://www.antdv.com/docs/vue/introduce-cn'
                    },
                    {
                        title:'elementUI',
                        icon:'/docs/navIcons/ele_logo.ico',
                        url:'https://element.eleme.cn/#/zh-CN/component/installation'
                    },
                    {
                        title:'uniapp',
                        icon:'/docs/navIcons/uni_logo.png',
                        url:'https://uniapp.dcloud.io/quickstart'
                    },
                    {
                        title:'React官方文档',
                        icon:'/docs/navIcons/react_logo.png',
                        url:'https://react.docschina.org/'
                    },{
                        title:'nodeJS文档',
                        icon:'/docs/navIcons/node_logo.png',
                        url:'http://nodejs.cn/api/'
                    },{
                        title:'express中文网',
                        icon:'/docs/navIcons/express-logo.png',
                        url:'https://www.expressjs.com.cn/'
                    },{
                        title:'小程序文档',
                        icon:'/docs/navIcons/wea_logo.ico',
                        url:'https://developers.weixin.qq.com/miniprogram/dev/component/'
                    },
                    {
                        title:'小程序UI库推荐',
                        icon:'/docs/navIcons/7.png',
                        url:'https://www.jianshu.com/p/4182f4a18cb6'
                    },
                    {
                        title:'MDN文档',
                        icon:'/docs/navIcons/mdn_logo.png',
                        url:'https://developer.mozilla.org/zh-CN/'
                    },
                    {
                        title:'webpack中文网',
                        icon:'/docs/navIcons/webpack_logo.ico',
                        url:'https://www.webpackjs.com/concepts/'
                    }, {
                        title:'ECharts',
                        icon:'/docs/navIcons/echarts_logo.png',
                        url:'https://www.echartsjs.com/zh/tutorial.html'
                    },{
                        title:'BootCDN',
                        icon:'/docs/navIcons/bootcdn_logo.ico',
                        url:'https://www.bootcdn.cn/'
                    },{
                        title:'github加速clone',
                        icon:'/docs/navIcons/7.png',
                        url:'https://github.zhlh6.cn/'
                    },{
                        title:'mockjs',
                        icon:'/docs/navIcons/mock_logo.svg',
                        url:'http://mockjs.com/'
                    },{
                        title:'廖雪峰网站',
                        icon:'/docs/navIcons/7.png',
                        url:'https://www.liaoxuefeng.com/'
                    },
                    {
                        title:'CSS张鑫旭',
                        icon:'/docs/navIcons/zxx_ico.png',
                        url:'https://www.zhangxinxu.com/wordpress/category/js/'
                    },
                    {
                        title:'木易杨',
                        icon:'/docs/navIcons/7.png',
                        url:'https://muyiy.cn/'
                    },{
                        title:'后端大佬',
                        icon:'/docs/navIcons/7.png',
                        url:'https://www.jmjc.tech/less/113'
                    },{
                        title:'奔跑的瓜牛',
                        icon:'/docs/navIcons/7.png',
                        url:'https://www.cnblogs.com/chenwenhao/category/1416194.html'
                    },
                    {
                        title:'swiper轮播图',
                        icon:'/docs/navIcons/swiper_logo.png',
                        url:'https://www.swiper.com.cn/api/index.html'
                    },
                    {
                        title:'better-scroll',
                        icon:'/docs/navIcons/better_logo.png',
                        url:'https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/'
                    },{
                        title:'草料二维码生成器',
                        icon:'/docs/navIcons/cli_logo.ico',
                        url:'https://cli.im/'
                    },{
                        title:'百度地图API',
                        icon:'/docs/navIcons/lbsyunlogo_icon.ico',
                        url:'http://lbsyun.baidu.com/index.php?title=jspopularGL'
                    },{
                        title:'rem,vw计算器',
                        icon:'/docs/navIcons/math_logo.ico',
                        url:'http://www.jq22.com/demo/jqueryremvw201812251323/'
                    },{
                        title:'CSS兼容转换',
                        icon:'/docs/navIcons/css_jianrong-logo.ico',
                        url:'http://autoprefixer.github.io/'
                    },{
                        title:'图片压缩tinypng',
                        icon:'/docs/navIcons/tinypng_logo.ico',
                        url:'https://tinypng.com/'
                    },{
                        title:'box-shadow阴影在线演示',
                        icon:'/docs/navIcons/shadow_logo.ico',
                        url:'https://www.html.cn/tool/css3Preview/Box-Shadow.html'
                    },{
                        title:'在线PS',
                        icon:'/docs/navIcons/ps-logo.ico',
                        url:'https://ps.gaoding.com/?hmsr=ivan-intro-juejin#/'
                    },{
                        title:'icon_font图标库',
                        icon:'/docs/navIcons/iconfont_logo.ico',
                        url:'https://www.iconfont.cn/'
                    },{
                        title:'GODELF取名',
                        icon:'/docs/navIcons/codelf_logo.f4ae25bd.png',
                        url:'https://unbug.github.io/codelf/'
                    },{
                        title:'设计导航',
                        icon:'/docs/navIcons/sheji_nav_logo.png',
                        url:'http://hao.shejidaren.com/'
                    },{
                        title:'字体图标库',
                        icon:'/docs/navIcons/font_logo.ico',
                        url:'https://fontawesome.dashgame.com/'
                    },{
                        title:'color工作台颜色搭配',
                        icon:'/docs/navIcons/color_logo.svg',
                        url:'https://www.webdesignrankings.com/resources/lolcolors/'
                    },{
                        title:'xiaopiu工作台',
                        icon:'/docs/navIcons/piu_logo.ico',
                        url:'https://www.xiaopiu.com/'
                    },{
                        title:'网易云音乐API',
                        icon:'/docs/navIcons/nec_music_logo.ico',
                        url:'https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=neteasecloudmusicapi'
                    },{
                        title:'免费摄影素材照片',
                        icon:'/docs/navIcons/free_logo.png',
                        url:'https://www.pexels.com/zh-cn/'
                    },
                ]
            }
        },
        methods:{
          handleClick(url){
                window.open(url)
          }
        },
        components:{
            NavItem
        }
    }
</script>

<style scoped>
.my-nav{
    padding-top:20px;
    display:flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: start;
}
</style>